FROM mcr.microsoft.com/playwright
RUN apt-get update && apt-get install -y \
    xvfb \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
ENV DISPLAY=:99
RUN Xvfb $DISPLAY -screen 0 1920x1080x24 &


RUN mkdir -p /app/node_modules && chown -R 1000:1000 /app
WORKDIR /app
COPY package.json yarn.lock ./
RUN npm install -g yarn && yarn install --frozen-lockfile && yarn global add dotenv
RUN npx playwright install --with-deps chromium chrome

RUN chown -R 1000:1000 /app
USER 1000
COPY package.json yarn.lock ./
CMD ["bash", "-c", "npm run xvfb:test"]
